discussion_board/urls.py
from django.contrib import admin
from django.urls import path,include
from boards import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('boards.url')),
    # path('',views.home,name='index'),
    #  path('about/',views.about,name='about'),

]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes import fields
# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=50,unique=True)
    description = models.CharField(max_length=150 )
    def __str__(self):
        return self.name
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board = models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)    
    created_by = models.ForeignKey(User,related_name='topics',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)    
    created_by = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
class Comment(models.Model):
    # content = models.TextField()
    comm = models.CharField(max_length=50)
   # document= models.ForeignKey(Document,related_name='comments',on_delete=models.CASCADE)  
   # protein= models.ForeignKey(Protein,related_name='comments',on_delete=models.CASCADE)   
    # topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)    
    content_type=models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id=models.PositiveIntegerField()
    content_object=GenericForeignKey('content_type','object_id')
    created_by = models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
    # def __str__(self):
    #     return self.comm
    # def save(self, *args, **kwargs):
    #     self.full_clean()
    #     return super().save(*args, **kwargs)   
class Document(models.Model):
    content = models.CharField(max_length=100,null=True)
    comments = GenericRelation(Comment)
    # topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)    
    created_by = models.ForeignKey(User,related_name='documents',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.content
    # def save(self, *args, **kwargs):
    #     self.full_clean()
    #     return super().save(*args, **kwargs)
    
class Protein(models.Model):
    AA_seq = models.TextField(max_length=10000)
    DNA_seq =  models.TextField(max_length=str(AA_seq)*3)
    content = models.CharField(max_length=100,null=True)
    created_by = models.ForeignKey(User,related_name='proteins',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
    comments = GenericRelation(Comment)
    def __str__(self):
        return self.content    
    # def save(self, *args, **kwargs):
    #     self.full_clean()
    #     return super().save(*args, **kwargs)
 


class Notification(models.Model):
    message = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True)
    type=  models.CharField(max_length=50)
    notificationlink_id=  models.CharField(max_length=50) # it should be id of :  document or protein or comment, so we could use notification when create object of them
    notificationlink=  models.CharField(max_length=50) # it should : document or protein or comment
    icon= models.CharField(max_length=50)
    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
# class Payer(models.Model):

#     name = models.CharField(blank=True, max_length=100)
#     # Nullable, but will enforce FK in clean/save:
#     payer_group = models.ForeignKey(PayerGroup, null=True, blank=True,)

#     def clean(self):
#         # Ensure every Payer is in a PayerGroup (but only via forms)
#         if not self.payer_group:
#             raise ValidationError(
#                 {'payer_group': 'Each Payer must belong to a PayerGroup.'})

#     def save(self, *args, **kwargs):
#         self.full_clean()
#         return super().save(*args, **kwargs)

#     def __str__(self):
#         return self.name    

boards/forms.py
from django import forms
from .models import Topic,Protein
class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
           attrs={'rows':5,'placeholder':'What is on your mind?'}
    )
  ,
    max_length=4000,
      help_text='The max length of the text is 4000',
    
    )
    class Meta:
        model = Topic
        fields = ['subject','message']
# class NewProteinForm(forms.ModelForm):

#   #   message = forms.CharField(widget=forms.Textarea(
#   #          attrs={'rows':5,'placeholder':'What is on your mind?'}
#   #   )
#   # ,
#   #   max_length=4000,
#   #     help_text='The max length of the text is 4000',
    
#   #   )
#     class Meta:
#         model = Protein
#         fields =['test']
        # fields = ['subject','message']

boards/views.py
from django.http.response import Http404
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, UserManager
from .models import Board,Topic
from .forms import NewTopicForm
from .models import Topic,Post
# Create your views here.
def home(request):

    boards = Board.objects.all()
    return render(request,'home.html',{'boards' : boards})
def about(request):
    return HttpResponse(request,"yes")        
def board_topics(request,board_id): 
#     try:
#     board = Board.objects.get(pk= board_id)        
#     except Board.DoesNotExist:
#          raise Http404
    board=get_object_or_404(Board,pk=board_id)
    return render(request,'topics.html',{'board' : board})
#     boards_names= []
#     for board in boards: 
#         boards_names.append(board.name) 
#     print(boards_names)      
#     response_html = '<br>'.join(boards_names)
#     return HttpResponse(response_html)

#     return HttpResponse(boards_names)
def new_topic(request,board_id): 
    board=get_object_or_404(Board,pk=board_id)  
#     if request.method== 'POST':
            
#          subject= request.POST['subject']  
#          message= request.POST['message']  
#          user= User.objects.first()
#          topic=Topic.objects.create(
#                  subject=subject,
#                  board=board,
#                  created_by=user


#          )
#          post=Post.objects.create(
#                  message=message,
#                  topic=topic,
#                  created_by=user
#          )
#          return redirect('board_topics',board_id=board.pk)
#     return render(request,'new_topic.html' ,{'board' : board})    
    form =NewTopicForm()
    user= User.objects.first()
    if request.method== 'POST':
        form =NewTopicForm(request.POST)   
        if form.is_valid():
          topic=form.save(commit=False)   
          topic.board = board 
          topic.created_by = user
          topic.save()
          post=Post.objects.create(
               message=form.cleaned_data.get('message'),
               created_by=user,
               topic=topic,
                       
          )
          return redirect('board_topics',board_id=board.pk)
    else:
         form =NewTopicForm()        
         return render(request,'new_topic.html' ,{'board' : board,'form':form})       
def input_type(request):
    # form =NewProteinForm()
    user= User.objects.first()
    # if request.method== 'POST':
    #     form =NewProteinForm(request.POST)   
        # if form.is_valid():
        #   topic=form.save(commit=False)   
        #   topic.board = board 
        #   topic.created_by = user
        #   topic.save()
        #   post=Post.objects.create(
        #        message=form.cleaned_data.get('message'),
        #        created_by=user,
        #        topic=topic,
                       
        #   )
        #   return redirect('board_topics',board_id=board.pk)
    # else:
    #      form =NewProteinForm()   


    return render(request,'input.html') 
def test(req):
    return render(req,'test.html')    
    # return HttpResponse(request)    

templates/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8" >
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
</head>
<body>
<div class="container">
 <ol class="breadcrumb my-4">
  {% block breadcrumb %}{% endblock  %}
    </ol>

     {% block content %}{% endblock  %}

    </div>
</body>
{% comment %} <script src="basecontrol.js"></script> {% endcomment %}

   {% block scripts %}
<script src="{%static 'js/jquery-3.4.1.min.js'%}"></script>
<script src="{%static 'js/popper.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>
<script src="{%static 'js/basecontrol.js'%}">
 
{% comment %} var y = new BaseControl({ container: $("ab")}); {% endcomment %}
{% comment %} x.getDefaultMainElement();
 x.launch(); {% endcomment %}
</script>
  {% endblock %}
<script type="text/javascript">
var y = new BaseControl({ container: $("ab")});
</script>

</html>

templates/input copy 2.html
{% extends 'base.html' %}
{% block title %} Submission {% endblock  %}
{% block breadcrumb  %}
   
    <li class="breadcrumb-item active">Submission</li>
{% endblock  %}  
   {% block content %}
    <form method="post" >
 {% csrf_token %} 
 

 <div class="form-group">

 <label for="id_subject">Subject</label>
<input class="form-control" type="text" name="subject" id="id_subject" >
 
</div>
<div class="form-group">
 <labelfor="id_message" >Message</label>
<input  class="form-control"  type="text" name="message" id="id_message">

</div> 
<div class="form-group">
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
</div>
<div id="ab">

</div>
<div id="abc">

</div>
<div id="efg">
</div>
 <table >
                                    <div  id="marray" >
                                                                                        
                                    </div>
                                </table>
<a href="#" id="ab2">ABC</a>
<div id="foo">
<h1>Foo</h1>
</div>
<div id="id-SampleControl-abc">

</div>
<button class="btn btn-success" type="submit">Add</button>
</form>




 



   {% endblock  %}
  {% block scripts %}
 {{ block.super }}
  <script  type="text/javascript">
const v_efg=document.getElementById("efg");
const xyz=document.querySelector("#foo");
var v_xyz=new BaseControl(xyz);
v_xyz.mainElement=$("#foo");
v_xyz.mainElementID="1";
v_xyz.launch();
var aaa=new BaseControl("aaaa");
aaa.launch();
var v_2=new SampleControl(v_xyz);
v_2.launch();
{% comment %} const v_xyz2=document.querySelector(v_2); {% endcomment %}
{% comment %} const v_xyz2=document.querySelector(v_xyz); {% endcomment %}
const List=new SampleControl(v_efg);
List.mainElement="<h1>";

    dodo =new SampleControl("abc");
    {% comment %} BaseControl.allExist(dodo); {% endcomment %}
 yy=new BaseControl("x");
 yy.launch();
 {% comment %} ff=document.querySelector(yy); {% endcomment %}
 xy=new BaseControl("abc");
 
 op=new SampleControl({IDs: "ab"});


 xy.getDefaultMainElement();
 op._initUI();
   (function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('ab').appendChild(newNode);
            })();
xr=new SampleControl("abc");
xr.IDs="abc";
let pop=document.getElementById("abc");
 o2=new SampleControl(pop);
 o2.IDs.headerElement="bobo";
$("ab2").click(
function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('abc').appendChild(newNode);
            }

);
coco=new SampleControl("<h1>testing</h1>");
coco._initUI();
base=new BaseControl("<h1>testing</h1>");
nou=new Sub("nice");
{% comment %} nou.createBy("abc"); {% endcomment %}
$('#abc').append("<h1>hello worldo</h1>");
for (i=0;i<5;i++)
{
  $("marray").append("<h1>hello marry</h1>");
}


</script>
{% endblock %}


    {% comment %} <script  type="text/javascript">
 yy=new BaseControl("x");

</script>
   {% endcomment %}

{% comment %} <script  src="basecontrol.js" >
var x = new BaseControl("ab");
x.getDefaultMainElement();
 x.launch(); {% endcomment %}
{% comment %} const y = new BaseControl({
 "ab"
});  {% endcomment %}
{% comment %} </script> {% endcomment %}

templates/input copy 3.html
{% extends 'base.html' %}
{% block title %} Submission {% endblock  %}
{% block breadcrumb  %}
   
    <li class="breadcrumb-item active">Submission</li>
{% endblock  %}  
   {% block content %}
    <form method="post" >
 {% csrf_token %} 
 

 <div class="form-group">

 <label for="id_subject">Subject</label>
<input class="form-control" type="text" name="subject" id="id_subject" >
 
</div>
<div class="form-group">
 <labelfor="id_message" >Message</label>
<input  class="form-control"  type="text" name="message" id="id_message">

</div> 
<div class="form-group">
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
</div>
<div id="ab">

</div>
<div id="abc">

</div>
<div id="efg">
</div>


 <table >
                                    <div  id="marray" >
                                                                                        
                                    </div>
                                </table>
<a href="#" id="ab2">ABC</a>
<div id="foo">
<h1>Foo</h1>
</div>
<div id="id-SampleControl-abc">

</div>
<button class="btn btn-success" type="submit">Add</button>
</form>

<form onsubmit="guardarNumeros()">
 <p>Please insert the items</p>
 <input type="text" id="box">
 <input type="submit" value="Submit">
</form>

<label id="stat1"></label>

 



   {% endblock  %}
  {% block scripts %}
 {{ block.super }}
  <script  type="text/javascript">
const v_efg=document.getElementById("efg");
const xyz=document.querySelector("#foo");
var v_xyz=new BaseControl(xyz);
v_xyz.mainElement=$("#foo");
v_xyz.mainElementID="1";
v_xyz.disableAutoWrapper=true;
v_xyz.launch();
{% comment %} $("#box").append("<div></div>"); {% endcomment %}
$('.'+v_xyz.absoluteID(v_xyz.mainElementID)).append("<input type='text'/>");

var aaa=new BaseControl("aaaa");
aaa.launch();
var v_2=new SampleControl(v_xyz);
v_2.mainElementID="1";
{% comment %} v_2. {% endcomment %}
v_2.launch();
 v_2.IDs.headerElement=3;
v_2._initUI();
document.querySelector("." +v_2.absoluteID(v_2.IDs.headerElement)).innerHTML="new";
var b=v_2.absoluteID(v_2.IDs.headerElement);

{% comment %} $('.'+v_xyz.absoluteID(v_xyz.mainElementID)).append("<input type='text'/>"); {% endcomment %}
{% comment %}  v_2.absoluteID(v_2.IDs.headerElement) {% endcomment %}
{% comment %} const v_xyz2=document.querySelector(v_2); {% endcomment %}
{% comment %} const v_xyz2=document.querySelector(v_xyz); {% endcomment %}
const List=new SampleControl(v_efg);
List.mainElement="<h1>";

    dodo =new SampleControl("abc");
    {% comment %} BaseControl.allExist(dodo); {% endcomment %}
 yy=new BaseControl("x");
 yy.launch();
 {% comment %} ff=document.querySelector(yy); {% endcomment %}
 xy=new BaseControl("abc");
 
 op=new SampleControl({IDs: "ab"});


 xy.getDefaultMainElement();
 op._initUI();
   (function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('ab').appendChild(newNode);
            })();
xr=new SampleControl("abc");
xr.IDs="abc";
let pop=document.getElementById("abc");
 o2=new SampleControl(pop);
 o2.IDs.headerElement="bobo";
$("ab2").click(
function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('abc').appendChild(newNode);
            }

);
coco=new SampleControl("<h1>testing</h1>");
coco._initUI();
base=new BaseControl("<h1>testing</h1>");
nou=new Sub("nice");
{% comment %} nou.createBy("abc"); {% endcomment %}
{% comment %}  !== -1 {% endcomment %}
$('#abc').append("<h1>hello worldo</h1>");
for (i=0;i<5;i++)
{
  $("marray").append("<h1>hello marry</h1>");
}
var items = [];
 var status ="";
function guardarNumeros() {
   
  boxvalue = document.getElementById('box').value;
   status = items.indexOf(boxvalue) !==-1 ? 'this value already exists' : 'this value was added' ;
 document.querySelector("#stat1").innerHTML=status;
    document.getElementById("stat1").value = status;
    if(status=="this value was added")
    {
  items.push(boxvalue);  
    }
  console.log(items);
  return false;
}
</script>
{% endblock %}


    {% comment %} <script  type="text/javascript">
 yy=new BaseControl("x");

</script>
   {% endcomment %}

{% comment %} <script  src="basecontrol.js" >
var x = new BaseControl("ab");
x.getDefaultMainElement();
 x.launch(); {% endcomment %}
{% comment %} const y = new BaseControl({
 "ab"
});  {% endcomment %}
{% comment %} </script> {% endcomment %}

templates/input copy 4.html
{% extends 'base.html' %}
{% block title %} Submission {% endblock  %}
{% block breadcrumb  %}
   
    <li class="breadcrumb-item active">Submission</li>
{% endblock  %}  
   {% block content %}
    <form method="post" >
 {% csrf_token %} 
 

 <div class="form-group">

 <label for="id_subject">Subject</label>
<input class="form-control" type="text" name="subject" id="id_subject" >
 
</div>
<div class="form-group">
 <labelfor="id_message" >Message</label>
<input  class="form-control"  type="text" name="message" id="id_message">

</div> 
<div class="form-group">
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
</div>
<div id="ab">

</div>
<div id="abc">

</div>
<div id="efg">
</div>


 <table >
                                    <div  id="marray" >
                                                                                        
                                    </div>
                                </table>
<a href="#" id="ab2">ABC</a>
<div id="foo">
<h1>Foo</h1>
</div>
<div id="id-SampleControl-abc">

</div>
<button class="btn btn-success" type="submit">Add</button>
</form>

<form onsubmit="guardarNumeros()">
 <p>Please insert the items</p>
 <input type="text" id="box">
 <input type="submit" value="Submit">
</form>

<label id="stat1"></label>

<select  id="selectNumber" class="btn btn-secondary dropdown-toggle">
    <option>Choose a number</option>
</select> 



   {% endblock  %}
  {% block scripts %}
 {{ block.super }}
  <script  type="text/javascript">
const v_efg=document.getElementById("efg");
const xyz=document.querySelector("#foo");
var v_xyz=new BaseControl(xyz);
v_xyz.mainElement=$("#foo");
v_xyz.mainElementID="1";
v_xyz.disableAutoWrapper=true;
v_xyz.launch();
{% comment %} $("#box").append("<div></div>"); {% endcomment %}
$('.'+v_xyz.absoluteID(v_xyz.mainElementID)).append("<input type='text'/>");

var aaa=new BaseControl("aaaa");
aaa.launch();
var v_2=new SampleControl(v_xyz);
v_2.mainElementID="1";
{% comment %} v_2. {% endcomment %}
v_2.launch();
 v_2.IDs.headerElement=3;
v_2._initUI();
{% comment %} BaseControl.initialIDPrefix = "xx"; {% endcomment %}
var v_3=new Sub(v_xyz);
v_3.mainElementID=3;
 v_3.IDs.headerElement=3;
v_3.launch();

document.querySelector("." +v_2.absoluteID(v_2.IDs.headerElement)).innerHTML="new";
var b=v_2.absoluteID(v_2.IDs.headerElement);

{% comment %} $('.'+v_xyz.absoluteID(v_xyz.mainElementID)).append("<input type='text'/>"); {% endcomment %}
{% comment %}  v_2.absoluteID(v_2.IDs.headerElement) {% endcomment %}
{% comment %} const v_xyz2=document.querySelector(v_2); {% endcomment %}
{% comment %} const v_xyz2=document.querySelector(v_xyz); {% endcomment %}
const List=new SampleControl(v_efg);
List.mainElement="<h1>";

    dodo =new SampleControl("abc");
    {% comment %} BaseControl.allExist(dodo); {% endcomment %}
 yy=new BaseControl("x");
 yy.launch();
 {% comment %} ff=document.querySelector(yy); {% endcomment %}
 xy=new BaseControl("abc");
 
 op=new SampleControl({IDs: "ab"});


 xy.getDefaultMainElement();
 op._initUI();
   (function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('ab').appendChild(newNode);
            })();
xr=new SampleControl("abc");
xr.IDs="abc";
let pop=document.getElementById("abc");
 o2=new SampleControl(pop);
 o2.IDs.headerElement="bobo";
$("ab2").click(
function(){
                var countup = this;
                var newNode = document.createElement('div');
                newNode.SampleControl = 'textNode news content';
                newNode.innerHTML = 'this created div contains a class while created!!!';
                document.getElementById('abc').appendChild(newNode);
            }

);
coco=new SampleControl("<h1>testing</h1>");
coco._initUI();
base=new BaseControl("<h1>testing</h1>");
nou=new Sub("nice");
{% comment %} nou.createBy("abc"); {% endcomment %}
{% comment %}  !== -1 {% endcomment %}
$('#abc').append("<h1>hello worldo</h1>");
for (i=0;i<5;i++)
{
  $("marray").append("<h1>hello marry</h1>");
}
var items = [];
 var status ="";
function guardarNumeros() {
   
  boxvalue = document.getElementById('box').value;
   status = items.indexOf(boxvalue) !==-1 ? 'this value already exists' : 'this value was added' ;
 document.querySelector("#stat1").innerHTML=status;
    document.getElementById("stat1").value = status;
    if(status=="this value was added")
    {
  items.push(boxvalue);  
 var select = document.getElementById("selectNumber");
 var el = document.createElement("option");
  el.value=boxvalue;
select.appendChild(el);
el.textContent=boxvalue;

    }
  console.log(items);

  return false;
}

{% comment %} 

var select = document.getElementById("selectNumber");
var options = ["1", "2", "3", "4", "5"];

for(var i = 0; i < items.length; i++) {
    var opt = options[i];
    var el = document.createElement("option");
    el.textContent = opt;
    el.value = opt;
    select.appendChild(el);
} {% endcomment %}
</script>
{% endblock %}


    {% comment %} <script  type="text/javascript">
 yy=new BaseControl("x");

</script>
   {% endcomment %}

{% comment %} <script  src="basecontrol.js" >
var x = new BaseControl("ab");
x.getDefaultMainElement();
 x.launch(); {% endcomment %}
{% comment %} const y = new BaseControl({
 "ab"
});  {% endcomment %}
{% comment %} </script> {% endcomment %}

templates/input copy.html
{% extends 'base.html' %}
{% block title %} Submission {% endblock  %}
{% block breadcrumb  %}
   
    <li class="breadcrumb-item active">Submission</li>
{% endblock  %}  
   {% block content %}
    <form method="post" >
 {% csrf_token %} 
 

 <div class="form-group">

 <label for="id_subject">Subject</label>
<input class="form-control" type="text" name="subject" id="id_subject" >
 
</div>
<div class="form-group">
 <labelfor="id_message" >Message</label>
<input  class="form-control"  type="text" name="message" id="id_message">

</div> 
<div class="form-group">
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown link
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
</div>
<div id="ab">

</div>
<button class="btn btn-success" type="submit">Add</button>
</form>




   



   {% endblock  %}

<script  src="basecontrol.js" >
let x = new BaseControl("ab");
x.getDefaultMainElement();
 x.launch();
</script>

templates/new_topic.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8" >
    <title>{{board.name}}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
</head>
<body>
<div class="container">
 <ol class="breadcrumb my-4">
    <li class="breadcrumb-item "> <a href="{% url 'home' %}">Boards </a>  </li>
    
    <li class="breadcrumb-item active">  <a href="{% url 'board_topics' board.pk %}" > {{board.name}} </a> </li>
    <li class="breadcrumb-item active"> New </li>
    </ol>
      <div class='col-md-12'>
    <form method="post" novalidate>
 {% csrf_token %} 
 {{form.as_p}}
{% comment %} 
 <div class="form-group">

 <label for="id_subject">Subject</label>
<input class="form-control" type="text" name="subject" id="id_subject" >
 
</div>
<div class="form-group">
 <labelfor="id_message" >Message</label>
<input  class="form-control"  type="text" name="message" id="id_message">

</div> {% endcomment %}

<button class="btn btn-success" type="submit">Add</button>
</form>
</div>
</div>

</body>

</html>